const ContactEmail = (name, email, message) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>New Contact Message | Cloud-UBA</title>
  <style>
    /* Inline CSS for maximum email client compatibility */
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: #f4f4f5;
      color: #334155;
      margin: 0;
      padding: 40px 20px;
    }
    .container {
      max-width: 540px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 8px;
      border: 1px solid #e2e8f0;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
      overflow: hidden;
    }
    .brand-header {
      background-color: #4f46e5;
      padding: 24px 30px;
      text-align: left;
    }
    .brand-logo {
      color: #ffffff;
      font-size: 22px;
      font-weight: 700;
      letter-spacing: 0.5px;
      margin: 0;
    }
    .brand-subtitle {
      color: #e0e7ff;
      font-size: 13px;
      margin-top: 4px;
      font-weight: 500;
    }
    .content {
      padding: 30px;
    }
    .header {
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 1px solid #f1f5f9;
      font-size: 18px;
      font-weight: 600;
      color: #0f172a;
    }
    .field {
      margin-bottom: 20px;
    }
    .label {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #64748b;
      margin-bottom: 6px;
      font-weight: 600;
    }
    .value {
      font-size: 15px;
      line-height: 1.6;
      color: #1e293b;
    }
    .message-box {
      background-color: #f8fafc;
      padding: 16px;
      border-radius: 6px;
      border: 1px solid #e2e8f0;
      margin-top: 8px;
      white-space: pre-wrap; /* Keeps the user's paragraph breaks */
      color: #334155;
      font-size: 14px;
      line-height: 1.6;
    }
    .link {
      color: #4f46e5;
      text-decoration: none;
      font-weight: 500;
    }
    .footer {
      background-color: #f8fafc;
      padding: 20px 30px;
      font-size: 12px;
      color: #64748b;
      text-align: center;
      border-top: 1px solid #e2e8f0;
    }
    .footer p {
      margin: 4px 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="brand-header">
      <div class="brand-logo">Cloud-UBA</div>
      <div class="brand-subtitle">Security Administration</div>
    </div>

    <div class="content">
      <div class="header">New Support Request</div>
      
      <div class="field">
        <div class="label">Sender Name</div>
        <div class="value"><strong>${name}</strong></div>
      </div>

      <div class="field">
        <div class="label">Email Address</div>
        <div class="value"><a href="mailto:${email}" class="link">${email}</a></div>
      </div>

      <div class="field">
        <div class="label">Message Payload</div>
        <div class="value message-box">${message}</div>
      </div>
    </div>

    <div class="footer">
      <p>This is an automated notification generated by the Cloud-UBA system.</p>
      <p>&copy; ${new Date().getFullYear()} Cloud-UBA. All rights reserved.</p>
    </div>
  </div>
</body>
</html>
`;

module.exports = ContactEmail;